# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
   
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    
    - name: Archive build artifacts
      run: cd /home/runner/work/S1SolApp/S1SolApp/CoreApp/bin/Release/ && tar -czvf S1SolApp.tar.gz net8.0
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: /home/runner/work/S1SolApp/S1SolApp/CoreApp/bin/Release/S1SolApp.tar.gz
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Display files in working directory
        run: ls

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.KEY}}
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H 159.203.174.5  >> ~/.ssh/known_hosts
         
      - name: Transfer build artifacts to DO Droplet
        uses: appleboy/scp-action@master
        with:
          host: 159.203.174.5
          username: root
          key: ${{secrets.KEY}}
          source: S1SolApp.tar.gz
          target: /var/www/temp/
      
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: 159.203.174.5
          username:  root
          key: ${{secrets.KEY}}
          script: |
            sudo systemctl stop app.service
            cd ..
            cd /var/www/
            rm -rf app
            mkdir app
            cd /var/www/temp/
            tar -xvf S1SolApp.tar.gz -C /var/www/app
            cd /var/www/app/
            mv net8.0/* .
            sudo systemctl restart app.service
            cd /var/www/temp/
            rm -rf S1SolApp.tar.gz
