name: .NET Framework App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      run: nuget restore DerekPersonalMVC.sln

    - name: Build
      run: msbuild DerekPersonalMVC.sln /p:Configuration=Release

    - name: Archive build artifacts
      run: tar -czvf YourApp.tar.gz -C path\to\Release\Directory\ .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: YourApp.tar.gz

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: package

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{secrets.KEY}}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -H 159.203.174.5 >> ~/.ssh/known_hosts

    - name: Transfer build artifacts to DO Droplet
      uses: appleboy/scp-action@master
      with:
        host: 159.203.174.5
        username: root
        key: ${{secrets.KEY}}
        source: YourApp.tar.gz
        target: /var/www/temp/

    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: 159.203.174.5
        username: root
        key: ${{secrets.KEY}}
        script: |
          sudo systemctl stop yourapp.service
          cd /var/www/
          mkdir -p yourapp
          cd /var/www/temp/
          tar -xvf YourApp.tar.gz -C /var/www/yourapp
          sudo systemctl start yourapp.service
          cd /var/www/temp/
          rm -rf YourApp.tar.gz
